# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRLbNlNJGLPR8T3e5YtM9ZoFXjorPHUk
"""

print("Lute ou fuja")

name = input("qual o seu name: ")

print("seja bem vindo: " , name)

def menu():

   print("aparaceu um inimigo a sua frente")

   print("1 - vc luta")
   print("2 - ou vai fugir")
jogo_rodando = True
while jogo_rodando:
    menu()
    op = input("oq se vai fazer: ")

    if op == "1":
     print("escolha seu personagem")
     print("1 - goku")
     print("2 - Naruto")
     jj = input("digite o numero do seu personagem: ")
     if jj == "1":
      print("vc usa um kamehameha e elimina por completo seu inimigo")
      print("1 - sim")
      print("2 - não")

      lk = input("vc quer continuar: ")

      if lk == "1":
        print("então aparece o zeno")
        print("vc vai pra cima dele")
        print("1 - sim")
        print("2 - não")
        jh = input("qual a sua escolha: ")
        if jh == "1":
          print("vc é apagado da existencia e morre")
          jogo_rodando = False
        if jh == "2":
         print("então vc vai embora")
         jogo_rodando = False

      elif lk == "2":
        print("fez a melhor escolha, deseja continuar ou sair do jogo")
        print("1 - sim")
        print("2 - sair")
        qw = input("faça a escolha: ")
        if qw == "1":
          print("sem querer o zeno apaga todo o universo e vc morre")
          jogo_rodando = False
        elif qw == "2":
          print("o jogo acaba")
          jogo_rodando = False

     elif jj  == "2":
       print("vc usa o rasengan e elimina por completo seu inimigo")
       print("vc vai continuar")
       print("1 - sim")
       print("2 - vou nada")

       uy = input("digite o numero da sua escolha: ")
       if uy == "1":
         print("certo, o madara aparece, ele ta deboa")
         print("1 - sim")
         print("2 - não")
         gd = input("vc ataca ele: ")

         if gd == "1":
           print("ele derrota vc, e vc morre")
           jogo_rodando = False
         elif gd == "2":
          print("vc vai pra casa")
          jogo_rodando = False
       elif uy == "2":
        print("o jogo acabou")
        jogo_rodando = False

    elif op == "2":
      print("então o jogo acabou")
      jogo_rodando = False

    input("aperte ENTER pra sair...")

